### ISSUE TITLE
Truffle deploy

### ISSUE THREAD

**Issue by Yusurax** [pcaversaccio/erc20-permit-upgradeable#1]
Hi thank you for sharing. Would you please to create sample deployment and upgrade migrations  file for truffle. Thankyou. 

And do you prefer to use transparent or UUPS for upgradable ? appreciate your answer

**Comment by pcaversaccio** [comment]
You can use Hardhat with Truffle: https://hardhat.org/guides/truffle-migration.html. I will however not convert this project into a Truffle project. You can do that - just fork it and adjust.

My recommendation is in general UUPS pattern since it is more gas-efficient and the upgrade is handled by the implementation itself but I do recommend not using upgradable patterns at all if possible.
